/* SPDX-License-Identifier: GPL-2.0-only */

#include <device/device.h>

#if CONFIG_X58_PRO_E_B06WD_SEABIOS_INPUT || \
	CONFIG_X58_PRO_E_B06WC_INTEGRATED_PLATFORM || \
	CONFIG_X58_PRO_E_B06WB_TCO_HALT || \
	CONFIG_X58_PRO_E_B06WA_HPET_DECODE || \
	CONFIG_X58_PRO_E_B06VZ_FIXED_RESOURCES || \
	CONFIG_X58_PRO_E_B06VY_IOAPIC_MASK || \
	CONFIG_X58_PRO_E_B06VX_AHCI_USB_TRACE || \
	CONFIG_X58_PRO_E_B06VW_ICH10_AHCI_MMIO || \
	CONFIG_X58_PRO_E_B06VV_ICH10_PCS_SCLK || \
	CONFIG_X58_PRO_E_B06VU_ICH10_AHCI_ROUTE || \
	CONFIG_X58_PRO_E_B06VQ_ICHBASE1 || \
	CONFIG_X58_PRO_E_B06VQ_PLATRO1 || \
	CONFIG_X58_PRO_E_B06VQ_USB_TRACE1 || \
	CONFIG_X58_PRO_E_B06VT_ICH10_SATA_CLOCK || \
	CONFIG_X58_PRO_E_B06VS_ICH10_AHCI_PORTS || \
	CONFIG_X58_PRO_E_B06VR_ICH10_AHCI_MAP || \
	CONFIG_X58_PRO_E_B06VQ_ICH10_EHCI_INIT || \
	CONFIG_X58_PRO_E_B06VP_LAPIC_EXTINT || \
	CONFIG_X58_PRO_E_B06VO_IOHBUSNO_ROUTE || \
	CONFIG_X58_PRO_E_B06VN_IOU0_PCIE_PHYS_VBIOS
#include "b06vn_pci.h"
#elif CONFIG_X58_PRO_E_B06VM_AUTO_PCI_VGA_IPXE
#include "b06vm_pci.h"
#elif CONFIG_X58_PRO_E_B06VF_SEABIOS_ENTRY
#include "b06vf_payload.h"
#endif

struct chip_operations mainboard_msi_x58_pro_e_ops = {
	.name = CONFIG_X58_PRO_E_SPD_SERIAL_INDEPENDENT ?
		"MSI X58 Pro-E experimental development SPD10" :
		CONFIG_X58_PRO_E_B06WK_ACPI_REPAIR ?
		"MSI X58 Pro-E experimental B06WK ACPI repair" :
		CONFIG_X58_PRO_E_B06WJ_ACPI_PLATFORM ?
		"MSI X58 Pro-E experimental B06WJ ACPI platform" :
		CONFIG_X58_PRO_E_B06WI_VENDOR_IRQ_ACPI ?
		"MSI X58 Pro-E experimental B06WI exact IRQ/ACPI" :
		CONFIG_X58_PRO_E_B06WH_QUIET_USB_SEABIOS ?
		"MSI X58 Pro-E experimental B06WH automatic GPIO57 USB SeaBIOS" :
		CONFIG_X58_PRO_E_B06WG_AUTO_USB_SEABIOS ?
		"MSI X58 Pro-E experimental B06WG automatic GPIO57 USB SeaBIOS" :
		CONFIG_X58_PRO_E_B06WF_USB_LAB ?
		"MSI X58 Pro-E experimental B06WF late USB diagnostic lab" :
		CONFIG_X58_PRO_E_B06WE_ACPI_SAD_BDF_FIX ?
		"MSI X58 Pro-E experimental B06WE ACPI SAD BDF fix" :
		CONFIG_X58_PRO_E_B06WD_SEABIOS_INPUT ?
		"MSI X58 Pro-E experimental B06WD SeaBIOS input platform" :
		CONFIG_X58_PRO_E_B06WC_INTEGRATED_PLATFORM ?
		"MSI X58 Pro-E experimental B06WC integrated platform" :
		CONFIG_X58_PRO_E_B06WB_TCO_HALT ?
		"MSI X58 Pro-E experimental B06WB deterministic ICH10 TCO halt" :
		CONFIG_X58_PRO_E_B06WA_HPET_DECODE ?
		"MSI X58 Pro-E experimental B06WA quiescent ICH10 HPET decode" :
		CONFIG_X58_PRO_E_B06VZ_FIXED_RESOURCES ?
		"MSI X58 Pro-E experimental B06VZ fixed platform resources" :
		CONFIG_X58_PRO_E_B06VY_IOAPIC_MASK ?
		"MSI X58 Pro-E experimental B06VY deterministic ICH10 IOAPIC mask" :
		CONFIG_X58_PRO_E_B06VX_AHCI_USB_TRACE ?
		"MSI X58 Pro-E experimental B06VX AHCI/deferred USB trace" :
		CONFIG_X58_PRO_E_B06VW_ICH10_AHCI_MMIO ?
		"MSI X58 Pro-E experimental B06VW minimal ICH10 AHCI MMIO" :
		CONFIG_X58_PRO_E_B06VV_ICH10_PCS_SCLK ?
		"MSI X58 Pro-E experimental B06VV corrected ICH10 PCS/SCLK" :
		CONFIG_X58_PRO_E_B06VU_ICH10_AHCI_ROUTE ?
		"MSI X58 Pro-E experimental B06VU corrected ICH10 AHCI route" :
		CONFIG_X58_PRO_E_B06VQ_ICHBASE1 ?
		"MSI X58 Pro-E experimental B06VQ six-field ICH10 baseline" :
		CONFIG_X58_PRO_E_B06VQ_PLATRO1 ?
		"MSI X58 Pro-E experimental B06VQ read-only platform census" :
		CONFIG_X58_PRO_E_B06VQ_USB_TRACE1 ?
		"MSI X58 Pro-E experimental B06VQ deferred SeaBIOS USB trace" :
		CONFIG_X58_PRO_E_B06VT_ICH10_SATA_CLOCK ?
		"MSI X58 Pro-E experimental B06VT ICH10 SATA clock" :
		CONFIG_X58_PRO_E_B06VS_ICH10_AHCI_PORTS ?
		"MSI X58 Pro-E experimental B06VS ICH10 AHCI ports" :
		CONFIG_X58_PRO_E_B06VR_ICH10_AHCI_MAP ?
		"MSI X58 Pro-E experimental B06VR ICH10 AHCI map" :
		CONFIG_X58_PRO_E_B06VQ_ICH10_EHCI_INIT ?
		"MSI X58 Pro-E experimental B06VQ ICH10 EHCI init" :
		CONFIG_X58_PRO_E_B06VP_LAPIC_EXTINT ?
		"MSI X58 Pro-E experimental B06VP LAPIC ExtINT probe" :
		CONFIG_X58_PRO_E_B06VO_IOHBUSNO_ROUTE ?
		"MSI X58 Pro-E experimental B06VO IOHBUSNO routing probe" :
		CONFIG_X58_PRO_E_B06VN_IOU0_PCIE_PHYS_VBIOS ?
		"MSI X58 Pro-E experimental B06VN IOU0 PCIe/physical-VBIOS" :
		CONFIG_X58_PRO_E_B06VM_AUTO_PCI_VGA_IPXE ?
		"MSI X58 Pro-E experimental B06VM auto PCI/VGA/iPXE" :
		CONFIG_X58_PRO_E_B06VL_BROAD_HARD_GATE_SEABIOS ?
		"MSI X58 Pro-E experimental B06VL broad hard-gated SeaBIOS attempt" :
		CONFIG_X58_PRO_E_B06VK_Q_CANONICAL_CLASS_SEABIOS ?
		"MSI X58 Pro-E experimental B06VK profile-Q canonical-class SeaBIOS gate" :
		CONFIG_X58_PRO_E_B06VJ_COUPLED_PROFILE_Q_SEABIOS ?
		"MSI X58 Pro-E experimental B06VJ coupled profile-Q SeaBIOS gate" :
		CONFIG_X58_PRO_E_B06VI_COUPLED_PROFILE_O_SEABIOS ?
		"MSI X58 Pro-E experimental B06VI coupled profile-O SeaBIOS gate" :
		CONFIG_X58_PRO_E_B06VH_PRIMARY_WORKSPACE_REARM_SEABIOS ?
		"MSI X58 Pro-E experimental B06VH PRIMARY workspace/rearm SeaBIOS gate" :
		CONFIG_X58_PRO_E_B06VG_COUPLED_MINIT_SEABIOS ?
		"MSI X58 Pro-E experimental B06VG coupled MINIT/SeaBIOS gate" :
		CONFIG_X58_PRO_E_B06VF_SEABIOS_ENTRY ?
		"MSI X58 Pro-E experimental B06VF SeaBIOS entry probe" :
		CONFIG_X58_PRO_E_B06VE_HIGH_QPI_AUTO_HANDOFF ?
		"MSI X58 Pro-E experimental B06VE High-QPI DRAM ROMMON" :
		CONFIG_X58_PRO_E_B06VD_HIGH_QPI_CSI2A6_MINIT ?
		"MSI X58 Pro-E experimental B06VD paired CSI2A6 High-QPI MINIT observation" :
		CONFIG_X58_PRO_E_B06VC_HIGH_QPI_A0_4SET_MINIT ?
		"MSI X58 Pro-E experimental B06VC High-QPI A0 four-set MINIT observation" :
		CONFIG_X58_PRO_E_B06VB_HIGH_QPI_MINIT_OBSERVE ?
		"MSI X58 Pro-E experimental B06VB High-QPI MINIT observation" :
		CONFIG_X58_PRO_E_B06VA_HIGH_QPI_A0_SET ?
		"MSI X58 Pro-E experimental B06VA High-QPI A0 allowlist probe" :
		CONFIG_X58_PRO_E_B06V9_DETERMINISTIC_QPI_3PASS ?
		"MSI X58 Pro-E experimental B06V9 deterministic High-QPI CSI probe" :
		CONFIG_X58_PRO_E_B06V8_HIGH_QPI_3PASS ?
		"MSI X58 Pro-E experimental B06V8 High-QPI CSI probe" :
		CONFIG_X58_PRO_E_B06V7_ROBUST_SLOWQPI ?
		"MSI X58 Pro-E experimental B06V7 robust Slow-QPI DRAM ROMMON" :
		CONFIG_X58_PRO_E_B06V6_AUTO_HANDOFF ?
		"MSI X58 Pro-E experimental B06V6 DRAM ROMMON" :
		"MSI X58 Pro-E experimental bring-up",
#if CONFIG_X58_PRO_E_B06WC_INTEGRATED_PLATFORM || \
	CONFIG_X58_PRO_E_B06WB_TCO_HALT || \
	CONFIG_X58_PRO_E_B06WA_HPET_DECODE || \
	CONFIG_X58_PRO_E_B06VZ_FIXED_RESOURCES || \
	CONFIG_X58_PRO_E_B06VY_IOAPIC_MASK || \
	CONFIG_X58_PRO_E_B06VX_AHCI_USB_TRACE || \
	CONFIG_X58_PRO_E_B06VW_ICH10_AHCI_MMIO || \
	CONFIG_X58_PRO_E_B06VV_ICH10_PCS_SCLK || \
	CONFIG_X58_PRO_E_B06VU_ICH10_AHCI_ROUTE || \
	CONFIG_X58_PRO_E_B06VQ_ICHBASE1 || \
	CONFIG_X58_PRO_E_B06VQ_PLATRO1 || \
	CONFIG_X58_PRO_E_B06VQ_USB_TRACE1 || \
	CONFIG_X58_PRO_E_B06VT_ICH10_SATA_CLOCK || \
	CONFIG_X58_PRO_E_B06VS_ICH10_AHCI_PORTS || \
	CONFIG_X58_PRO_E_B06VR_ICH10_AHCI_MAP || \
	CONFIG_X58_PRO_E_B06VQ_ICH10_EHCI_INIT || \
	CONFIG_X58_PRO_E_B06VP_LAPIC_EXTINT || \
	CONFIG_X58_PRO_E_B06VO_IOHBUSNO_ROUTE || \
	CONFIG_X58_PRO_E_B06VN_IOU0_PCIE_PHYS_VBIOS
	.enable_dev = x58_b06vn_enable_dev,
#elif CONFIG_X58_PRO_E_B06VM_AUTO_PCI_VGA_IPXE
	.enable_dev = x58_b06vm_enable_dev,
#elif CONFIG_X58_PRO_E_B06VF_SEABIOS_ENTRY
	.enable_dev = x58_b06vf_enable_dev,
#endif
};
